<a href="https://colab.research.google.com/github/AliAoun/PracticeDbConfig_WebEng/blob/master/ChronicKidneyDiseasePrediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier

In [ ]:
df = pd.read_csv("Chronickidneydisease.csv")
df.head()

Bp     Sg   Al   Su  Rbc    Bu   Sc     Sod   Pot  Hemo    Wbcc  Rbcc  \
0  80.0  1.020  1.0  0.0  1.0  36.0  1.2  137.53  4.63  15.4  7800.0  5.20   
1  50.0  1.020  4.0  0.0  1.0  18.0  0.8  137.53  4.63  11.3  6000.0  4.71   
2  80.0  1.010  2.0  3.0  1.0  53.0  1.8  137.53  4.63   9.6  7500.0  4.71   
3  70.0  1.005  4.0  0.0  1.0  56.0  3.8  111.00  2.50  11.2  6700.0  3.90   
4  80.0  1.010  2.0  0.0  1.0  26.0  1.4  137.53  4.63  11.6  7300.0  4.60   

   Htn  Class  
0  1.0      1  
1  0.0      1  
2  0.0      1  
3  1.0      1  
4  0.0      1

In [ ]:
df.describe()

Bp          Sg          Al          Su         Rbc         Bu  \
count  400.000000  400.000000  400.000000  400.000000  400.000000  400.00000   
mean    76.455000    1.017712    1.015000    0.395000    0.882500   57.40550   
std     13.476536    0.005434    1.272329    1.040038    0.322418   49.28597   
min     50.000000    1.005000    0.000000    0.000000    0.000000    1.50000   
25%     70.000000    1.015000    0.000000    0.000000    1.000000   27.00000   
50%     78.000000    1.020000    1.000000    0.000000    1.000000   44.00000   
75%     80.000000    1.020000    2.000000    0.000000    1.000000   61.75000   
max    180.000000    1.025000    5.000000    5.000000    1.000000  391.00000   

              Sc         Sod         Pot        Hemo          Wbcc  \
count  400.00000  400.000000  400.000000  400.000000    400.000000   
mean     3.07235  137.529025    4.627850   12.526900   8406.090000   
std      5.61749    9.204273    2.819783    2.716171   2523.219976   
min      0.40000    4.500000    2.500000    3.100000   2200.000000   
25%      0.90000  135.000000    4.000000   10.875000   6975.000000   
50%      1.40000  137.530000    4.630000   12.530000   8406.000000   
75%      3.07000  141.000000    4.800000   14.625000   9400.000000   
max     76.00000  163.000000   47.000000   17.800000  26400.000000   

             Rbcc         Htn       Class  
count  400.000000  400.000000  400.000000  
mean     4.708275    0.369350    0.625000  
std      0.840315    0.482023    0.484729  
min      2.100000    0.000000    0.000000  
25%      4.500000    0.000000    0.000000  
50%      4.710000    0.000000    1.000000  
75%      5.100000    1.000000    1.000000  
max      8.000000    1.000000    1.000000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 14 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Bp      400 non-null    float64
 1   Sg      400 non-null    float64
 2   Al      400 non-null    float64
 3   Su      400 non-null    float64
 4   Rbc     400 non-null    float64
 5   Bu      400 non-null    float64
 6   Sc      400 non-null    float64
 7   Sod     400 non-null    float64
 8   Pot     400 non-null    float64
 9   Hemo    400 non-null    float64
 10  Wbcc    400 non-null    float64
 11  Rbcc    400 non-null    float64
 12  Htn     400 non-null    float64
 13  Class   400 non-null    int64  
dtypes: float64(13), int64(1)
memory usage: 43.9 KB


In [ ]:
df_duplicates = df[df.duplicated()]
df_duplicates.shape[0]

0

In [ ]:
df

Bp     Sg   Al   Su  Rbc    Bu   Sc     Sod   Pot  Hemo    Wbcc  Rbcc  \
0    80.0  1.020  1.0  0.0  1.0  36.0  1.2  137.53  4.63  15.4  7800.0  5.20   
1    50.0  1.020  4.0  0.0  1.0  18.0  0.8  137.53  4.63  11.3  6000.0  4.71   
2    80.0  1.010  2.0  3.0  1.0  53.0  1.8  137.53  4.63   9.6  7500.0  4.71   
3    70.0  1.005  4.0  0.0  1.0  56.0  3.8  111.00  2.50  11.2  6700.0  3.90   
4    80.0  1.010  2.0  0.0  1.0  26.0  1.4  137.53  4.63  11.6  7300.0  4.60   
..    ...    ...  ...  ...  ...   ...  ...     ...   ...   ...     ...   ...   
395  80.0  1.020  0.0  0.0  1.0  49.0  0.5  150.00  4.90  15.7  6700.0  4.90   
396  70.0  1.025  0.0  0.0  1.0  31.0  1.2  141.00  3.50  16.5  7800.0  6.20   
397  80.0  1.020  0.0  0.0  1.0  26.0  0.6  137.00  4.40  15.8  6600.0  5.40   
398  60.0  1.025  0.0  0.0  1.0  50.0  1.0  135.00  4.90  14.2  7200.0  5.90   
399  80.0  1.025  0.0  0.0  1.0  18.0  1.1  141.00  3.50  15.8  6800.0  6.10   

     Htn  Class  
0    1.0      1  
1    0.0      1  
2    0.0      1  
3    1.0      1  
4    0.0      1  
..   ...    ...  
395  0.0      0  
396  0.0      0  
397  0.0      0  
398  0.0      0  
399  0.0      0  

[400 rows x 14 columns]

In [ ]:
le = LabelEncoder()
df['Class'] = le.fit_transform(df['Class'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 14 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Bp      400 non-null    float64
 1   Sg      400 non-null    float64
 2   Al      400 non-null    float64
 3   Su      400 non-null    float64
 4   Rbc     400 non-null    float64
 5   Bu      400 non-null    float64
 6   Sc      400 non-null    float64
 7   Sod     400 non-null    float64
 8   Pot     400 non-null    float64
 9   Hemo    400 non-null    float64
 10  Wbcc    400 non-null    float64
 11  Rbcc    400 non-null    float64
 12  Htn     400 non-null    float64
 13  Class   400 non-null    int64  
dtypes: float64(13), int64(1)
memory usage: 43.9 KB


In [ ]:

X = df.drop(columns = ['Class'])
y = df['Class']



In [ ]:
scalar = StandardScaler()
X = scalar.fit_transform(X)
X

array([[ 2.63379226e-01,  4.21485600e-01, -1.18041644e-02, ...,
        -2.40505799e-01,  5.85900177e-01,  1.30997921e+00],
       [-1.96549998e+00,  4.21485600e-01,  2.34902872e+00, ...,
        -9.54773379e-01,  2.05537202e-03, -7.67209735e-01],
       [ 2.63379226e-01, -1.42107440e+00,  7.75140131e-01, ...,
        -3.59550396e-01,  2.05537202e-03, -7.67209735e-01],
       ...,
       [ 2.63379226e-01,  4.21485600e-01, -7.98748460e-01, ...,
        -7.16684186e-01,  8.24204178e-01, -7.67209735e-01],
       [-1.22254025e+00,  1.34276560e+00, -7.98748460e-01, ...,
        -4.78594992e-01,  1.41996418e+00, -7.67209735e-01],
       [ 2.63379226e-01,  1.34276560e+00, -7.98748460e-01, ...,
        -6.37321121e-01,  1.65826818e+00, -7.67209735e-01]])

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [ ]:
RF_C = RandomForestClassifier()
RF_C.fit(X_train, y_train)

y_pred_rfc = RF_C.predict(X_test)

accuracy_rfc = accuracy_score(y_test, y_pred_rfc)

confusion_matrix_rfc = confusion_matrix(y_test, y_pred_rfc)

report_rfc = classification_report(y_test, y_pred_rfc)


print("Random Forest Classifier:")
print(f"Accuracy: {accuracy_rfc*100}%")
print('Confusion Matrix: ')
print(confusion_matrix_rfc)
print('Classification Report:')
print(report_rfc)



Random Forest Classifier:
Accuracy: 100.0%
Confusion Matrix: 
[[28  0]
 [ 0 52]]
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        28
           1       1.00      1.00      1.00        52

    accuracy                           1.00        80
   macro avg       1.00      1.00      1.00        80
weighted avg       1.00      1.00      1.00        80



In [ ]:
DT_C = DecisionTreeClassifier()
DT_C.fit(X_train, y_train)
y_pred_dtc = DT_C.predict(X_test)

accuracy_dtc = accuracy_score(y_test, y_pred_dtc)

confusion_matrix_dtc = confusion_matrix(y_test, y_pred_dtc)

report_dtc = classification_report(y_test, y_pred_dtc)


print("Decision Tree Classifier:")
print(f"Accuracy: {accuracy_dtc*100}%")
print('DT Confusion Matrix: ')
print(confusion_matrix_dtc)
print('DT Classification Report:')
print(report_dtc)



Decision Tree Classifier:
Accuracy: 98.75%
DT Confusion Matrix: 
[[28  0]
 [ 1 51]]
DT Classification Report:
              precision    recall  f1-score   support

           0       0.97      1.00      0.98        28
           1       1.00      0.98      0.99        52

    accuracy                           0.99        80
   macro avg       0.98      0.99      0.99        80
weighted avg       0.99      0.99      0.99        80



In [ ]:
NB_C = GaussianNB()
NB_C.fit(X_train, y_train)
y_pred_nbc = NB_C.predict(X_test)

accuracy_nbc = accuracy_score(y_test, y_pred_nbc)

confusion_matrix_nbc = confusion_matrix(y_test, y_pred_nbc)

report_nbc = classification_report(y_test, y_pred_nbc)


print("Naive Bayes Classifier:")
print(f"Accuracy: {accuracy_nbc*100}%")
print('NB Confusion Matrix: ')
print(confusion_matrix_nbc)
print('NB Classification Report:')
print(report_nbc)


Naive Bayes Classifier:
Accuracy: 93.75%
NB Confusion Matrix: 
[[27  1]
 [ 4 48]]
NB Classification Report:
              precision    recall  f1-score   support

           0       0.87      0.96      0.92        28
           1       0.98      0.92      0.95        52

    accuracy                           0.94        80
   macro avg       0.93      0.94      0.93        80
weighted avg       0.94      0.94      0.94        80

